# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralWidget)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seedLabel = QtWidgets.QLabel(self.centralWidget)
        self.seedLabel.setObjectName("seedLabel")
        self.horizontalLayout.addWidget(self.seedLabel)
        self.seedValue = QtWidgets.QLineEdit(self.centralWidget)
        self.seedValue.setObjectName("seedValue")
        self.horizontalLayout.addWidget(self.seedValue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.enemyCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.enemyCheck.setObjectName("enemyCheck")
        self.verticalLayout.addWidget(self.enemyCheck)
        self.noAbilityCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.noAbilityCheck.setToolTip("")
        self.noAbilityCheck.setStatusTip("")
        self.noAbilityCheck.setObjectName("noAbilityCheck")
        self.verticalLayout.addWidget(self.noAbilityCheck)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.romDisplay = QtWidgets.QLineEdit(self.centralWidget)
        self.romDisplay.setReadOnly(True)
        self.romDisplay.setObjectName("romDisplay")
        self.horizontalLayout_2.addWidget(self.romDisplay)
        self.findROMButton = QtWidgets.QPushButton(self.centralWidget)
        self.findROMButton.setObjectName("findROMButton")
        self.horizontalLayout_2.addWidget(self.findROMButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.randomizeButton = QtWidgets.QPushButton(self.centralWidget)
        self.randomizeButton.setObjectName("randomizeButton")
        self.verticalLayout.addWidget(self.randomizeButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.urlLabel = QtWidgets.QLabel(self.centralWidget)
        self.urlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.urlLabel.setObjectName("urlLabel")
        self.verticalLayout.addWidget(self.urlLabel)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kirby\'s Adventure Randomizer"))
        self.title.setText(_translate("MainWindow", "Kirby: Nightmare in Dream Land Randomizer - Version: "))
        self.seedLabel.setText(_translate("MainWindow", "Seed:"))
        self.enemyCheck.setText(_translate("MainWindow", "Randomize Enemies"))
        self.noAbilityCheck.setText(_translate("MainWindow", "Randomize Enemies without Abilities"))
        self.findROMButton.setText(_translate("MainWindow", "Choose ROM Location"))
        self.randomizeButton.setText(_translate("MainWindow", "Randomize!"))
        self.urlLabel.setText(_translate("MainWindow", "https://github.com/Aquova/KND-Rando"))

