# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralWidget)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seedLabel = QtWidgets.QLabel(self.centralWidget)
        self.seedLabel.setObjectName("seedLabel")
        self.horizontalLayout.addWidget(self.seedLabel)
        self.seedValue = QtWidgets.QLineEdit(self.centralWidget)
        self.seedValue.setObjectName("seedValue")
        self.horizontalLayout.addWidget(self.seedValue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.enemyCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.enemyCheck.setObjectName("enemyCheck")
        self.verticalLayout.addWidget(self.enemyCheck)
        self.starRodCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.starRodCheck.setObjectName("starRodCheck")
        self.verticalLayout.addWidget(self.starRodCheck)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.orangeColor = QtWidgets.QRadioButton(self.centralWidget)
        self.orangeColor.setObjectName("orangeColor")
        self.gridLayout.addWidget(self.orangeColor, 2, 0, 1, 1)
        self.randomColor = QtWidgets.QRadioButton(self.centralWidget)
        self.randomColor.setObjectName("randomColor")
        self.gridLayout.addWidget(self.randomColor, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.defaultColor = QtWidgets.QRadioButton(self.centralWidget)
        self.defaultColor.setChecked(True)
        self.defaultColor.setObjectName("defaultColor")
        self.gridLayout.addWidget(self.defaultColor, 1, 1, 1, 1)
        self.carbonColor = QtWidgets.QRadioButton(self.centralWidget)
        self.carbonColor.setObjectName("carbonColor")
        self.gridLayout.addWidget(self.carbonColor, 5, 2, 1, 1)
        self.redColor = QtWidgets.QRadioButton(self.centralWidget)
        self.redColor.setObjectName("redColor")
        self.gridLayout.addWidget(self.redColor, 1, 2, 1, 1)
        self.chalkColor = QtWidgets.QRadioButton(self.centralWidget)
        self.chalkColor.setObjectName("chalkColor")
        self.gridLayout.addWidget(self.chalkColor, 5, 0, 1, 1)
        self.emeraldColor = QtWidgets.QRadioButton(self.centralWidget)
        self.emeraldColor.setObjectName("emeraldColor")
        self.gridLayout.addWidget(self.emeraldColor, 3, 1, 1, 1)
        self.yellowColor = QtWidgets.QRadioButton(self.centralWidget)
        self.yellowColor.setObjectName("yellowColor")
        self.gridLayout.addWidget(self.yellowColor, 2, 1, 1, 1)
        self.greenColor = QtWidgets.QRadioButton(self.centralWidget)
        self.greenColor.setObjectName("greenColor")
        self.gridLayout.addWidget(self.greenColor, 2, 2, 1, 1)
        self.cherryColor = QtWidgets.QRadioButton(self.centralWidget)
        self.cherryColor.setObjectName("cherryColor")
        self.gridLayout.addWidget(self.cherryColor, 3, 0, 1, 1)
        self.oceanColor = QtWidgets.QRadioButton(self.centralWidget)
        self.oceanColor.setObjectName("oceanColor")
        self.gridLayout.addWidget(self.oceanColor, 3, 2, 1, 1)
        self.sapphireColor = QtWidgets.QRadioButton(self.centralWidget)
        self.sapphireColor.setObjectName("sapphireColor")
        self.gridLayout.addWidget(self.sapphireColor, 4, 0, 1, 1)
        self.grapeColor = QtWidgets.QRadioButton(self.centralWidget)
        self.grapeColor.setObjectName("grapeColor")
        self.gridLayout.addWidget(self.grapeColor, 4, 1, 1, 1)
        self.chocolateColor = QtWidgets.QRadioButton(self.centralWidget)
        self.chocolateColor.setObjectName("chocolateColor")
        self.gridLayout.addWidget(self.chocolateColor, 4, 2, 1, 1)
        self.snowColor = QtWidgets.QRadioButton(self.centralWidget)
        self.snowColor.setObjectName("snowColor")
        self.gridLayout.addWidget(self.snowColor, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.romDisplay = QtWidgets.QLineEdit(self.centralWidget)
        self.romDisplay.setReadOnly(True)
        self.romDisplay.setObjectName("romDisplay")
        self.horizontalLayout_2.addWidget(self.romDisplay)
        self.findROMButton = QtWidgets.QPushButton(self.centralWidget)
        self.findROMButton.setObjectName("findROMButton")
        self.horizontalLayout_2.addWidget(self.findROMButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.randomizeButton = QtWidgets.QPushButton(self.centralWidget)
        self.randomizeButton.setObjectName("randomizeButton")
        self.verticalLayout.addWidget(self.randomizeButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.urlLabel = QtWidgets.QLabel(self.centralWidget)
        self.urlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.urlLabel.setObjectName("urlLabel")
        self.verticalLayout.addWidget(self.urlLabel)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kirby: Nightmare in Dream Land Randomizer"))
        self.title.setText(_translate("MainWindow", "Kirby: Nightmare in Dream Land - Version: "))
        self.seedLabel.setText(_translate("MainWindow", "Seed:"))
        self.enemyCheck.setText(_translate("MainWindow", "Randomize Enemies"))
        self.starRodCheck.setText(_translate("MainWindow", "Use Star Rod"))
        self.orangeColor.setText(_translate("MainWindow", "Orange"))
        self.randomColor.setText(_translate("MainWindow", "Random"))
        self.label.setText(_translate("MainWindow", "Kirby Color:"))
        self.defaultColor.setText(_translate("MainWindow", "Default (Pink)"))
        self.carbonColor.setText(_translate("MainWindow", "Carbon"))
        self.redColor.setText(_translate("MainWindow", "Red"))
        self.chalkColor.setText(_translate("MainWindow", "Chalk"))
        self.emeraldColor.setText(_translate("MainWindow", "Emerald"))
        self.yellowColor.setText(_translate("MainWindow", "Yellow"))
        self.greenColor.setText(_translate("MainWindow", "Green"))
        self.cherryColor.setText(_translate("MainWindow", "Cherry"))
        self.oceanColor.setText(_translate("MainWindow", "Ocean"))
        self.sapphireColor.setText(_translate("MainWindow", "Sapphire"))
        self.grapeColor.setText(_translate("MainWindow", "Grape"))
        self.chocolateColor.setText(_translate("MainWindow", "Chocolate"))
        self.snowColor.setText(_translate("MainWindow", "Snow"))
        self.findROMButton.setText(_translate("MainWindow", "Choose ROM Location"))
        self.randomizeButton.setText(_translate("MainWindow", "Randomize!"))
        self.urlLabel.setText(_translate("MainWindow", "https://github.com/Aquova/KNDL-Rando"))

